# Generated by Django 3.0.3 on 2020-03-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200330_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deliverycharge',
        ),
    ]
