# Generated by Django 3.0.3 on 2020-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_deliverycharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('unit1', models.CharField(max_length=100)),
                ('unit2', models.CharField(max_length=100)),
                ('unit3', models.CharField(max_length=100)),
                ('unit4', models.CharField(max_length=100)),
                ('unit5', models.CharField(max_length=100)),
                ('unit6', models.CharField(max_length=100)),
                ('unit7', models.CharField(max_length=100)),
                ('unit8', models.CharField(max_length=100)),
                ('unit9', models.CharField(max_length=100)),
                ('unit10', models.CharField(max_length=100)),
            ],
        ),
    ]
